version: '3.8'

services:
  # --- Redis 配置 ---
  redis:
    image: redis:alpine3.22
    container_name: redis-dev
    restart: always
    ports:
      - "6379:6379" # 宿主机:容器
    # 如果要持久化数据，取消下面两行的注释
    # volumes:
    #   - ./redis-data:/data
    command: redis-server --appendonly yes # 开启AOF持久化

  # --- Nacos 配置 ---
  nacos:
    image: nacos/nacos-server:v2.5.2 # 建议指定版本，避免latest变动
    container_name: nacos-dev
    restart: always
    environment:
      - MODE=standalone # 必填！必须是单机模式，否则启动报错
      - JVM_XMS=256m    # 限制一下内存，省得它吃太饱
      - JVM_XMX=256m
    ports:
      - "8848:8848" # 控制台端口
      - "9848:9848" # Nacos 2.0+ 必须映射的 gRPC 端口
      - "9849:9849" # Nacos 2.0+ 必须映射的 gRPC 端口
    # 如果要持久化配置，取消下面两行的注释
    # volumes:
    #   - ./nacos-logs:/home/nacos/logs
    
  # --- MinIO 配置 (对象存储) ---
  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: minio-dev
    restart: always
    ports:
      - "9000:9000" # API 端口 (后端代码连这个)
      - "9001:9001" # 控制台端口 (浏览器访问这个)
    environment:
      # 设置管理员账号密码 (对应你 application.yml 里的配置)
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    # 启动命令：指定数据目录并固定控制台端口
    command: server /data --console-address ":9001"

  # --- RabbitMQ 配置 (消息队列) ---
  rabbitmq:
    image: rabbitmq:4.2.1-management-alpine
    container_name: rabbitmq-dev
    restart: always
    ports:
      - "5672:5672"   # 消息通讯端口 (后端代码连这个)
      - "15672:15672" # 管理界面端口 (浏览器访问这个)
    environment:
      # 设置默认账号密码 (建议与 application.yml 保持一致)
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  # --- Elasticsearch 配置 (搜索引擎) ---
  elasticsearch:
    image: elasticsearch:9.2.2
    container_name: es-dev
    restart: always
    ports:
      - "9200:9200" # Http 端口 (后端代码连这个)
      - "9300:9300" # Tcp 端口 (集群通信)
    environment:
      - "discovery.type=single-node"    # 单机模式
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # 限制内存！ES默认吃内存很凶，学生电脑建议限制在512M-1G
      - "xpack.security.enabled=false"  # 关闭安全验证 (开发方便，不用配置复杂的证书和密码)